version: '3.1'

services:
  ghost:
    image: ghost:3.2-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - "./ghost:/var/lib/ghost/content"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: h3ll0w0rld
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: h3ll0w0rld
    volumes:
      - "./database:/var/lib/mysql"
