apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7 # ghost:3.2-alpine compatibility
        # image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "h3ll0w0rld" # change this
        - name: MYSQL_USER
          value: "ghost_user"
        - name: MYSQL_PASSWORD
          value: "h3ll0w0rld"
        - name: MYSQL_DATABASE
          value: "ghost"
